# Generated by Django 5.0.6 on 2024-06-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
